---
# install_chrony/tasks/main.yml

- name: 'Install chrony without a reboot'
  ansible.builtin.package:
    name: 'chrony'
  when:
    - 'not (ansible_os_family == "Suse" and ansible_distribution_major_version | int <= 12)'
    - 'not ansible_os_family == "openSUSE MicroOS"'
    - 'not ansible_os_family == "openSUSE Leap Micro"'
    - 'not ansible_pkg_mgr == "atomic_container"'

- name: 'Install chrony with reboot on openSUSE MicroOS / openSUSE Leap Micro'
  ansible.builtin.package:
    name: 'chrony'
  when:
    - '
      ansible_os_family == "openSUSE MicroOS"
      or ansible_os_family == "openSUSE Leap Micro"
      '
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'

- name: 'Flush handlers to reboot the system, if needed'
  ansible.builtin.meta: flush_handlers
