---
# install_chrony/tasks/main.yml

- name: 'Install chrony'
  package:
    name: 'chrony'
  when: '(ansible_distribution == "SLES" or ansible_distribution == "openSUSE Leap") and ansible_distribution_major_version > "12"'

- name: 'check if chrony is installed'
  command:
  args:
    cmd: 'rpm -q chrony'
    warn: 'false'
  register: 'check_for_chrony'
  changed_when: 'false'
  failed_when: 'false'
  check_mode: 'false'
  when: 'ansible_distribution == "openSUSE MicroOS"'

- name: 'Install chrony using transactional updates'
  command: '/usr/sbin/transactional-update --non-interactive pkg install chrony'
  when: 'ansible_distribution == "openSUSE MicroOS" and "is not installed" in check_for_chrony.stdout'
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'
