---
# install_chrony/tasks/main.yml

- name: 'Install chrony without a reboot'
  ansible.builtin.package:
    name: 'chrony'
  when:
    - 'not (ansible_os_family == "Suse" and ansible_distribution_major_version <= "12")'
    - 'ansible_os_family != "openSUSE MicroOS"'
    - 'ansible_os_family != "openSUSE Leap Micro"'

- name: 'Install chrony with reboot on openSUSE MicroOS / openSUSE Leap Micro'
  ansible.builtin.package:
    name: 'chrony'
  when:
    - '
      ansible_os_family == "openSUSE MicroOS"
      or ansible_os_family == "openSUSE MicroOS"
      '
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'
